=== api-evangelist/airbyte/json-schema/airbyte-connection-create-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/airbyte/refs/heads/main/json-schema/airbyte-connection-create-request-schema.json",
  "title": "ConnectionCreateRequest",
  "description": "ConnectionCreateRequest schema from Airbyte API",
  "type": "object",
  "properties": {
    "name": {
      "description": "Optional name of the connection",
      "type": "string"
    },
    "sourceId": {
      "format": "uuid",
      "type": "string"
    },
    "destinationId": {
      "format": "uuid",
      "type": "string"
    },
    "configurations": {
      "$ref": "#/components/schemas/StreamConfigurations"
    },
    "schedule": {
      "$ref": "#/components/schemas/AirbyteApiConnectionSchedule"
    },
    "dataResidency": {
      "deprecated": true,
      "x-speakeasy-deprecation-message": "We no longer support modifying dataResidency on Community and Enterprise connections. All connections will use the dataResidency of their associated workspace.",
      "type": "string"
    },
    "namespaceDefinition": {
      "$ref": "#/components/schemas/NamespaceDefinitionEnum"
    },
    "namespaceFormat": {
      "type": "string",
      "description": "Used when namespaceDefinition is 'custom_format'. If blank then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\" then behaves like namespaceDefinition = 'source'.",
      "default": null,
      "example": "${SOURCE_NAMESPACE}"
    },
    "prefix": {
      "type": "string",
      "description": "Prefix that will be prepended to the name of each stream when it is written to the destination (ex. \u201cairbyte_\u201d causes \u201cprojects\u201d => \u201cairbyte_projects\u201d).",
      "default": ""
    },
    "nonBreakingSchemaUpdatesBehavior": {
      "$ref": "#/components/schemas/NonBreakingSchemaUpdatesBehaviorEnum"
    },
    "status": {
      "$ref": "#/components/schemas/ConnectionStatusEnum"
    },
    "tags": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Tag"
      }
    }
  },
  "required": [
    "sourceId",
    "destinationId"
  ]
}

=== api-evangelist/airbyte/examples/airbyte-connection-create-request-example.json
{
  "name": "example-name",
  "sourceId": "abc123def456",
  "destinationId": "abc123def456",
  "configurations": "example-value",
  "schedule": "example-value",
  "dataResidency": "abc123def456",
  "namespaceDefinition": "example-namespacedefinition",
  "namespaceFormat": "example-namespaceformat",
  "prefix": "example-value",
  "nonBreakingSchemaUpdatesBehavior": "example-value",
  "status": "active",
  "tags": [
    "example-value"
  ]
}
